services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
      container_name: website
    environment:
      - NODE_ENV=production
    networks:
      - proxy

networks:
  proxy:
    external: true